# Generated by Django 4.0.2 on 2022-02-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
